# Generated by Django 4.2 on 2023-05-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0024_alter_customer_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="credit",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=5
            ),
        ),
    ]
