# Generated by Django 4.2 on 2023-05-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0025_customer_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="credit",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=5, null=True
            ),
        ),
    ]
