# Generated by Django 4.1.7 on 2023-03-26 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="barber",
            name="region",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="region",
        ),
    ]
