# Generated by Django 4.1.8 on 2023-04-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0002_remove_barber_region_remove_customer_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
