# Generated by Django 4.1.8 on 2023-04-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0003_alter_customer_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
