# Generated by Django 4.1.8 on 2023-04-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0004_alter_customer_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="/default_profile.png",
                error_messages={"invalid": "Image files only"},
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
        migrations.AlterField(
            model_name="barber",
            name="password",
            field=models.CharField(default="213", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(default="123", max_length=255, unique=True),
        ),
    ]
