# Generated by Django 4.1.8 on 2023-04-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0005_customer_profile_picture_alter_barber_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barber",
            name="password",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
