# Generated by Django 4.1.7 on 2023-04-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Barber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BarberShop", models.CharField(max_length=255)),
                ("Owner", models.CharField(max_length=255)),
                ("Parvaneh", models.CharField(max_length=10, unique=True)),
                ("phone_Number", models.CharField(max_length=11, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.CharField(max_length=255)),
            ],
        ),
    ]
