# Generated by Django 4.1.7 on 2023-04-05 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0002_alter_barber_barbershop_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="barbershop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="barbers",
                to="Barber.barber",
                to_field="BarberShop",
            ),
        ),
    ]
