# Generated by Django 4.1.7 on 2023-04-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0008_barber_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="barber",
            name="rate",
        ),
    ]
