# Generated by Django 4.1.7 on 2023-04-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0010_barber_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barber",
            name="rate",
            field=models.FloatField(default=1),
        ),
    ]
