# Generated by Django 4.2 on 2023-04-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barber', '0020_alter_barber_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='rate',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='rate',
            name='stars',
            field=models.IntegerField(),
        ),
    ]
