# Generated by Django 4.1.8 on 2023-04-08 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0020_alter_barber_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barber",
            name="rate",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="rate",
            name="stars",
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name="BarberShopImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("background", models.ImageField(upload_to="Barber/backg")),
                ("logo", models.ImageField(upload_to="Barber/Logo")),
                (
                    "barbershop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="Barber.barber",
                    ),
                ),
            ],
        ),
    ]
