# Generated by Django 4.1.8 on 2023-04-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0022_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="rate",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="rate",
            name="password",
            field=models.CharField(
                default=1234, max_length=128, verbose_name="password"
            ),
            preserve_default=False,
        ),
    ]
