# Generated by Django 4.2 on 2023-04-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0022_barber_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="barber",
            name="area",
            field=models.CharField(default=" ", max_length=255),
        ),
        migrations.AddField(
            model_name="barber",
            name="background",
            field=models.ImageField(
                null=True, upload_to="", verbose_name="Barber/backg"
            ),
        ),
        migrations.AddField(
            model_name="barber",
            name="logo",
            field=models.ImageField(
                null=True, upload_to="", verbose_name="Barber/Logo"
            ),
        ),
    ]
