# Generated by Django 4.2 on 2023-04-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0023_barber_area_barber_background_barber_logo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BarberShopImages",
        ),
    ]
