# Generated by Django 4.1.8 on 2023-04-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0021_alter_barber_rate_alter_rate_stars"),
        ("Barber", "0023_rate_last_login_rate_password"),
    ]

    operations = []
