# Generated by Django 4.2 on 2023-04-15 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0024_delete_barbershopimages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="barber",
            name="email",
        ),
    ]
