# Generated by Django 4.2 on 2023-04-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0025_remove_barber_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barber",
            name="background",
            field=models.ImageField(null=True, upload_to="Barber/backg"),
        ),
        migrations.AlterField(
            model_name="barber",
            name="logo",
            field=models.ImageField(null=True, upload_to="Barber/Logo"),
        ),
    ]
