# Generated by Django 4.2 on 2023-04-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0029_alter_barber_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barber",
            name="background",
            field=models.ImageField(upload_to="Barber/backg"),
        ),
        migrations.AlterField(
            model_name="barber",
            name="logo",
            field=models.ImageField(upload_to="Barber/Logo"),
        ),
    ]
