# Generated by Django 4.2 on 2023-04-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0030_alter_barber_background_alter_barber_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barber",
            name="background",
            field=models.ImageField(
                default="default_profile.png", upload_to="Barber/backg"
            ),
        ),
        migrations.AlterField(
            model_name="barber",
            name="logo",
            field=models.ImageField(
                default="default_profile.png", upload_to="Barber/Logo"
            ),
        ),
    ]
