# Generated by Django 4.2 on 2023-04-16 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Barber", "0031_alter_barber_background_alter_barber_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barber",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
