# Generated by Django 4.2 on 2023-04-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0033_alter_barber_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barber",
            name="area",
            field=models.CharField(max_length=255),
        ),
    ]
