# Generated by Django 4.2 on 2023-04-16 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Barber", "0034_alter_barber_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barber",
            name="BarberShop",
            field=models.CharField(max_length=255, unique=True, verbose_name="user"),
        ),
        migrations.AlterField(
            model_name="barber",
            name="Owner",
            field=models.CharField(max_length=255, verbose_name="user"),
        ),
        migrations.AlterField(
            model_name="barber",
            name="Parvaneh",
            field=models.CharField(max_length=10, unique=True, verbose_name="user"),
        ),
        migrations.AlterField(
            model_name="barber",
            name="address",
            field=models.CharField(max_length=255, verbose_name="user"),
        ),
        migrations.AlterField(
            model_name="barber",
            name="area",
            field=models.CharField(max_length=255, verbose_name="user"),
        ),
        migrations.AlterField(
            model_name="barber",
            name="phone_Number",
            field=models.CharField(max_length=11, unique=True, verbose_name="user"),
        ),
        migrations.AlterField(
            model_name="barber",
            name="rate",
            field=models.FloatField(default=1, verbose_name="user"),
        ),
        migrations.AlterField(
            model_name="barber",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
