# Generated by Django 4.2 on 2023-04-22 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Barber", "0036_alter_barber_barbershop_alter_barber_owner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hair", "hair"),
                            ("skin", "skin"),
                            ("makeup", "makeup"),
                            ("nail", "nail"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="barber",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(blank=True, max_length=255)),
                ("price", models.FloatField(default=0)),
                (
                    "service_pic",
                    models.ImageField(
                        default="default_profile.png",
                        null=True,
                        upload_to="Barber/Service",
                    ),
                ),
                (
                    "catg",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="Barber.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="barber",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="Barber.barber",
            ),
        ),
    ]
