# Generated by Django 4.2 on 2023-04-22 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Barber", "0037_category_alter_barber_user_service_category_barber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="catg",
        ),
        migrations.AddField(
            model_name="service",
            name="barber",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="Barber.barber",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.CharField(
                choices=[
                    ("hair", "hair"),
                    ("skin", "skin"),
                    ("makeup", "makeup"),
                    ("nail", "nail"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="barber",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
