# Generated by Django 4.2 on 2023-04-25 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0013_alter_customer_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Barber", "0044_alter_barber_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barber",
            name="area",
            field=models.CharField(
                choices=[
                    ("Tehranpars", "Tehranpars"),
                    ("Nazi Abad", "Nazi Abad"),
                    ("Narmak", "Narmak"),
                    ("Tajrish", "Tajrish"),
                    ("Gheytariye", "Gheytariye"),
                    ("Marzdaran", "Marzdaran"),
                    ("Janat Abad", "Janat Abad"),
                    ("Vanak", "Vanak"),
                    ("Enghelab", "Enghelab"),
                    ("Valiasr", "Valiasr"),
                    ("Saadat Abad", "Saadat Abad"),
                    ("Piroozi", "Piroozi"),
                    ("Jordan", "Jordan"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="barber",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="OrderServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField()),
                (
                    "barber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barber",
                        to="Barber.barber",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to="Customer.customer",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="Barber.service",
                    ),
                ),
            ],
        ),
    ]
