# Generated by Django 4.2 on 2023-04-27 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0053_category_categoryservice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryservice",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categoryServices",
                to="Barber.category",
            ),
        ),
    ]
