# Generated by Django 4.2 on 2023-04-30 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0055_alter_barber_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderservices",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="Barber.categoryservice",
            ),
        ),
        migrations.DeleteModel(
            name="Service",
        ),
    ]
