# Generated by Django 4.2 on 2023-05-01 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0059_alter_barber_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderservices",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
