# Generated by Django 4.2 on 2023-05-01 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0060_orderservices_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderservices",
            unique_together={("barber", "time", "date")},
        ),
    ]
