# Generated by Django 4.2 on 2023-05-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0061_alter_orderservices_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderservices",
            name="status",
            field=models.CharField(
                choices=[
                    ("ordered", "ordered"),
                    ("confirmed", "confirmed"),
                    ("paid", "paid"),
                ],
                default="ordered",
                max_length=9,
            ),
        ),
    ]
