# Generated by Django 4.2 on 2023-05-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0066_alter_categoryservice_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderservices",
            options={"ordering": ["date", "time"]},
        ),
        migrations.AddField(
            model_name="orderservices",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="barber",
            name="BarberShop",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="barber",
            name="Parvaneh",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="category",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="orderservices",
            name="status",
            field=models.CharField(
                choices=[
                    ("ordering", "ordering"),
                    ("paid", "paid"),
                    ("BarberCancelled", "BarberCancelled"),
                    ("CustomerCancelled", "CustomerCancelled"),
                    ("CustomerNotCome", "CustomerNotCome"),
                    ("Done", "Done"),
                ],
                default="ordering",
                max_length=20,
            ),
        ),
    ]
