# Generated by Django 4.2 on 2023-05-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0067_alter_orderservices_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderservices",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
