# Generated by Django 4.2 on 2023-05-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0067_alter_orderservices_options_orderservices_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryservice",
            name="price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="categoryservice",
            name="service",
            field=models.CharField(max_length=255),
        ),
    ]
