# Generated by Django 4.2 on 2023-05-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0068_orderservices_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderservices",
            name="totalPrice",
            field=models.FloatField(default=1),
        ),
    ]
