# Generated by Django 4.2 on 2023-05-17 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0068_alter_categoryservice_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BarberDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                ("description", models.TextField(max_length=256)),
                (
                    "img",
                    models.ImageField(
                        default="default_profile.png", upload_to="Barber/Description"
                    ),
                ),
                (
                    "barber",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barberDesc",
                        to="Barber.barber",
                    ),
                ),
            ],
        ),
    ]
