# Generated by Django 4.2 on 2023-05-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0069_orderservices_totalprice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderservices",
            name="totalPrice",
        ),
    ]
