# Generated by Django 4.2 on 2023-05-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0070_remove_orderservices_totalprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderservices",
            name="totalPrice",
            field=models.FloatField(default=0),
        ),
    ]
