# Generated by Django 4.2.1 on 2023-05-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0071_alter_barber_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="barber",
            name="expire_date",
            field=models.DateField(null=True),
        ),
    ]
