# Generated by Django 4.2 on 2023-05-14 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0028_alter_customer_credit"),
        ("Barber", "0071_orderservices_totalprice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderservices",
            name="totalPrice",
        ),
        migrations.CreateModel(
            name="TotalPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.FloatField(default=0)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customerTotal",
                        to="Customer.customer",
                    ),
                ),
            ],
        ),
    ]
