# Generated by Django 4.2 on 2023-05-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0073_alter_totalprice_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barber",
            name="Parvaneh",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
