# Generated by Django 4.2.1 on 2023-05-28 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0073_alter_barber_expire_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barber",
            name="expire_date",
            field=models.DateField(default=datetime.date(2023, 6, 28)),
        ),
        migrations.AlterField(
            model_name="barberdescription",
            name="description",
            field=models.TextField(default=" ", max_length=256),
        ),
        migrations.AlterField(
            model_name="barberdescription",
            name="title",
            field=models.CharField(default=" ", max_length=40),
        ),
    ]
