# Generated by Django 4.2.1 on 2023-05-29 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0076_remove_barber_expire_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="barber",
            name="expire_date",
            field=models.DateField(default=datetime.date(2023, 6, 29)),
        ),
        migrations.AlterField(
            model_name="barberpremium",
            name="month",
            field=models.IntegerField(
                choices=[
                    (1, "1-month"),
                    (3, "3-month"),
                    (6, "6-month"),
                    (12, "12-month"),
                ],
                default=0,
            ),
        ),
    ]
