# Generated by Django 4.2.1 on 2023-05-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0079_alter_barberpremium_barber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="barber",
            name="expire_date",
        ),
    ]
