# Generated by Django 4.2.1 on 2023-05-30 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0080_remove_barber_expire_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barberdescription",
            name="description",
            field=models.TextField(default="description", max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="barberdescription",
            name="title",
            field=models.CharField(default="title", max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="barberpremium",
            name="expire_date",
            field=models.DateField(default=datetime.date(2023, 6, 30)),
        ),
        migrations.AlterField(
            model_name="barberpremium",
            name="month",
            field=models.IntegerField(
                choices=[
                    (1, "1-month"),
                    (3, "3-month"),
                    (6, "6-month"),
                    (12, "12-month"),
                ],
                default=0,
            ),
        ),
    ]
