# Generated by Django 4.2.1 on 2023-05-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0081_alter_barberdescription_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barberdescription",
            name="description",
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name="barberdescription",
            name="title",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="orderservices",
            name="status",
            field=models.CharField(
                choices=[
                    ("ordering", "ordering"),
                    ("confirmed", "confirmed"),
                    ("paid", "paid"),
                    ("BarberCancelled", "BarberCancelled"),
                    ("CustomerCancelled", "CustomerCancelled"),
                    ("CustomerNotCome", "CustomerNotCome"),
                    ("Done", "Done"),
                ],
                default="ordering",
                max_length=20,
            ),
        ),
    ]
