# Generated by Django 4.2.1 on 2023-06-01 12:25

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0029_alter_customer_user"),
        ("Barber", "0082_alter_barberdescription_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barberpremium",
            name="expire_date",
            field=models.DateField(default=datetime.date(2023, 7, 1)),
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "barber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="Barber.barber",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authors_ratings",
                        to="Customer.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("barber", "customer")},
            },
        ),
    ]
