# Generated by Django 4.2.1 on 2023-06-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0085_alter_barberpremium_expire_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoryservice",
            old_name="servicePic",
            new_name="servicepic",
        ),
    ]
