# Generated by Django 4.2.1 on 2023-06-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0086_rename_servicepic_categoryservice_servicepic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoryservice",
            old_name="servicepic",
            new_name="servicePic",
        ),
    ]
