# Generated by Django 4.2.1 on 2023-06-05 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Barber", "0089_alter_categoryservice_servicepic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barberpremium",
            name="expire_date",
            field=models.DateField(default=datetime.date(2023, 7, 5)),
        ),
    ]
